config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :cooks
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
  validates :city, :cuisine, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController

  def index
    @cooks = Cook.all
  end

  def show
    @cook = Cook.find(params[:id])
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)

    if @cook.save
      redirect_to @cook, notice: "Cook post was successfully created."
    else
      render :new
    end
  end

  def edit
    @cook = Cook.find(params[:id])
  end

  def update
    @cook = Cook.find(params[:id])

    if @cook.update(cook_params)
      redirect_to @cook, notice: "Cook was successfully edited."
    else
      render :edit
    end
  end

  def destroy
    @cook = Cook.find(params[:id])

    @cook.destroy
    redirect_to cooks_path, notice: "Cook was successfully destroyed."
  end

  def cook_params
    params.require(:cook).permit(:city, :cuisine, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cooks/_form.html.erb
<%= form_for cook do |f| %>

  <% if cook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cook.errors.count, "error") %> prohibited this cook from being saved:</h2>

      <ul>
        <% cook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/cooks/edit.html.erb
<h1>Edit Cook</h1>

<%= render "form", cook: @cook %>

app/views/cooks/index.html.erb
<div class="container">
  <h1>Find cooks near you</h1>
</div>

<div class="container">
  <%= link_to 'Home', root_path %>
</div>

<div class="container">
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Cuisine</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>

    <%@cooks.each do |cook| %>
    <tr>
      <td><%= link_to cook.name, cook %></td>
      <td><%=cook.cuisine%></td>
      <td><%=cook.city%></td>
      <td><%= link_to 'Show', cook %></td>
      <td><%= link_to 'Edit', edit_cook_path(cook) %></td>
      <td><%= button_to 'Destroy', cook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>

    </tbody>
  </table>
</div>

<div class="container">
  <%= link_to 'New cook', new_cook_path %>
</div>

app/views/cooks/new.html.erb
<h1>New Cook</h1>

<%= render "form", cook: @cook %>

app/views/cooks/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Cook:</strong>
  <%= @cook.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @cook.cuisine %>
</p>

<p>
  <strong>City:</strong>
  <%= @cook.city %>
</p>
</div>

<div class="container">
  <%= link_to 'Edit', edit_cook_path(@cook) %>
  <%= button_to 'Destroy', @cook, method: :delete %>
  <%= link_to 'Back', cooks_path %>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <li class="nav-item nav-link active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
      <li class="nav-item nav-link"><%= link_to "Find", posts_path %></li>
      <li class="nav-item nav-link">Sign in</li>
    </div>
  </div>
</nav>

<div class="container">
<h1>Batch-it!</h1>
</div>

<div class="container">
  <button type="button" class="btn btn-success">
    <%= link_to "Find cooks near you", cooks_path %>
  </button>
  <button type="button" class="btn btn-success">
  <%= link_to 'I am a cook', new_cook_path %>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #EEEEEE;">
    <%= yield %>
  </body>
</html>